config/routes.rb
Rails.application.routes.draw do
  get 'lowests/index'

  get 'skus/index'

  root to: 'sessions#new'
  get 'signup',to: 'users#new'
  get    'login' , to: 'sessions#new'
  post   'login' , to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :asins
  resources :skus
  resources :lowests
  resources :orders do
    patch 'update_all', on: :collection
  end
  resources :inventories do
    collection do
      patch 'arrived'
      get 'arrived_list'
    end
  end

end

app/models/asin.rb
class Asin < ActiveRecord::Base
      belongs_to :user
end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
  belongs_to :user
end

app/models/lowest.rb
class Lowest < ActiveRecord::Base
      belongs_to :user
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
end

app/models/sku.rb
class Sku < ActiveRecord::Base
  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << csv_column_names
      all.each do |product|
        csv << product.csv_column_values
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  validates :prefecture, presence: true
  validates :phone, presence: true, length: { maximum: 13 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  has_many :orders
  has_many :inventories
  has_many :asins
  has_many :lowests
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  private
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end
end

app/controllers/asins_controller.rb
class AsinsController < ApplicationController
  before_action :set_asin, only: [:edit, :update, :destroy]
  def index
    @asin = Asin.new
    @asins = Asin.all
  end
  def create
    @asin = current_user.asins.build(asin_params)
    if @asin.save
      redirect_to asins_path
    else
      render 'new'
    end
  end
  def edit
  end
  def update
    if @asin.update(asin_params)
      redirect_to asins_path , notice: '編集ました'
    else
      render 'edit'
    end
  end
      private
  def asin_params
    params.require(:asin).permit(:jan, :asin,:weight,:height,:width,:length)
  end
  def set_asin
    @asin = Asin.find(params[:id])
  end
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  before_action :set_stock, only: [:edit, :update, :destroy]
  
  def index
    @stock = Inventory.new
    @stocks = current_user.inventories.where(arrived: nil).order(created_at: :desc)
  end
  def create
    @stock = current_user.inventories.build(stock_params)
    if @stock.save
      redirect_to inventories_path
    else
      render 'new'
    end
  end
  def edit
  end
  def update
    if @stock.update(stock_params)
      redirect_to inventories_path , notice: '配送業者を打ち込みました'
    else
      render 'edit'
    end
  end
  def arrived
    @stocks = Inventory.find(params[:stock_ids])
    #Sbinding.pry
      @stocks.each do |stock|
        stock.update_attribute(:arrived,1)
      end
      #render inventory_path(current_user)
  end
  
  def arrived_list
      @stocks = current_user.inventories.where.not(arrived: nil).order(created_at: :desc)
      render 'arrived'
  end
      private
  def stock_params
    params.require(:inventory).permit(:jan, :volume,:total_price,:asin,:shipfee,:price)
  end
  def set_stock
    @stock = Inventory.find(params[:id])
  end
end

app/controllers/login_page_controller.rb
class LoginPageController < ApplicationController
  def home
  end
end

app/controllers/lowests_controller.rb
class LowestsController < ApplicationController
  def index
    @lowest = Lowest.new
    @lowests = Lowest.all
  end
  def create
    @lowest = current_user.lowests.build(research_params)
    if @lowest.save
      binding.pry
      @asin = @lowest.asin
      @url = "http://www.amazon.co.jp/gp/offer-listing/"+ @asin
      @doc = Nokogiri::HTML(open(@url).read)
      @doc.xpath('//span[@class ="a-size-large a-color-price olpOfferPrice a-text-bold"]/').each do |node|
      @lowest.update_attribute(:amazon,node)
      end

      redirect_to lowests_path
    else
      render 'new'
    end
  end
  def update
  end
      private
  def research_params
    params.require(:lowest).permit(:asin)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    before_action :logged_in_user
    def index
        @orders = current_user.orders.where(shipfee: nil).order(created_at: :desc)
        @shipped_orders = current_user.orders.where.not(shipfee: nil).order(created_at: :desc)
    end
    
    def update_all
        @orders = Order.find(params[:order_ids])
        @shipping_fee = params[:shipping_fee]
        if params[:shipping_way] == '小型SAL'
            @total_weight = 0
            @orders.each do |order|
                #binding.pry
                sku = order.sku
                weight = Asin.find_by(sku:sku).weight
                @total_weight += weight.to_i
            end
            @orders.each do |order|
                sku = order.sku
                weight = Asin.find_by(sku:sku).weight                
                shipping_fee = @shipping_fee.to_i*weight.to_i/@total_weight.to_i
                order.update_attribute(:shipfee,shipping_fee)
            end
            redirect_to orders_path
        elsif params[:shiping_way] == 'SAL'
        elsif params[:shiping_way] == 'Pメール'
        elsif params[:shiping_way] == 'Dメール'
        else
        end
            
            
            
            
        puts params[:orders]
        puts "!!!!!!!!!!!!!!!!!"
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      flash[:info] = "logged in as #{@user.name}"
      redirect_to orders_path
    else
      flash[:danger] = 'invalid email/password combination'
      render 'new'
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/skus_controller.rb
class SkusController < ApplicationController
  def index
    @sku = Sku.new
    @skus = Sku.all
=begin    
    respond_for do |format|
      format.html
      format.xls { send_data @sku.to_csv(col_sep: "\t") }
    end
=end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @orders = @user.orders.order(created_at: :desc)
    #@order = Order.find(params[:id])
  end
  def edit
   @user = User.find(params[:id])
    unless current_user == @user
    redirect_to root_path, notice: 'loginし直してください'
    end
  end
  def update
    @user = User.find(params[:id])
    unless current_user == @user
    redirect_to root_path, notice: 'loginし直してください'
    end
    if @user.update(user_params)
      redirect_to root_path , notice: '基本情報を編集しました'
    else
      render 'edit'
    end
  end
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to the Rich World!"
      redirect_to @user
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :password,:email,:prefecture,:phone,
                                 :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end

  def store_location
    session[:forwarding_url] = request.url if request.get?
  end
end

app/views/asins/_form.html.erb
<%= form_for(@asin) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :asin, placeholder: "ASINを入力してください" %>
  </div>
  <div class="field">
    <%= f.number_field :width, placeholder: "横の長さを入力してください" %>
  </div>
  <div class="field">
    <%= f.number_field :length, placeholder: "縦の長さの価格を入力してください" %>
  <div class="field">
    <%= f.number_field :height , placeholder: "高さを入力してください"%>
  </div>
  <div class="field">
    <%= f.number_field :weight , placeholder: "重さを入力してください"%>
  </div>
  <div class="field">
    <%= f.number_field :jan , placeholder: "janを入力してください"%>
  </div>
 <%= f.submit "Post", class: "btn btn-primary" %>
 <% end %>

app/views/asins/edit.html.erb
<h1>ASINの更新</h1>

<%= render 'asins/form' %>

app/views/asins/index.html.erb
<%= form_for(@asin) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_field :asin, placeholder: "ASINを入力してください" %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>
      <ol class="asins">
      <div  class="tabele-responsive">
      <table class="table">
        <thead>
          <tr>
            <th>ASIN</th>
            <th>商品名</th>
            <th>横</th>
            <th>縦</th>
            <th>高さ</th>
            <th>重さ</th>
            <th>JANコード</th>
            <th></th>
          </tr>
        </thead>
        <% @asins.each do |asin| %>
        <tbody>
          <tr>
            <td><%= asin.asin %></td>
            <td><%= asin.title %></td>
            <td><%= asin.width%></td>
            <td><%= asin.length %></td>
            <td><%= asin.height %></td>
            <td><%= asin.weight %></td>
            <td><%= asin.jan%></td>
            <td><%= link_to "edit" , edit_asin_path(asin) %></td>
            </tr>
        </tbody>
        <% end %>
      </table>
  　　</div>
      </ol>

app/views/inventories/_form.html.erb
<%= form_for(@stock) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :asin, placeholder: "ASINを入力してください" %>
  </div>
  <div class="field">
    <%= f.number_field :volume, placeholder: "個数を入力してください" %>
  </div>
  <div class="field">
    <%= f.number_field :price, placeholder: "1個当たりの価格を入力してください" %>
  <div class="field">
    <%= f.number_field :shipfee , placeholder: "送料を入力してください"%>
  </div>
 <%= f.submit "Post", class: "btn btn-primary" %>
 <% end %>

app/views/inventories/arrived.html.erb
<% if current_user.inventories.any? %>
      <ol class="stocks">
      <div  class="tabele-responsive">
      <table class="table">
        <thead>
          <tr>
            <th>発注日</th>
            <th>ASIN</th>
            <th>商品名</th>
            <th>発注数</th>
            <th>仕入れ価格</th>
            <th>送料</th>
            <th>仕入れ先</th>
            <th>前月推定販売個数</th>
            <th>配送業者</th>
            <th>追跡番号</th>
            <th>予定到着日</th>
          </tr>
        </thead>

        <% @stocks.each do |stock| %>
        <tbody>
          <tr>
            <td><%= stock.created_at %></td>
            <td><%= stock.asin %></td>
            <td><%#= Asin.find_by(asin: stock.asin).title%></td>
            <td><%= stock.volume %></td>
            <td><%= stock.price %></td>
            <td><%= stock.shipfee%></td>
            <td><%=  %></td>
            <td><%=  %></td>
            <td><%=  %></td>
            <td><%=  %></td>
            <td><%=  %></td>
            </tr>
        </tbody>
        <% end %>
      </table>
  　　</div>
      </ol>
    <% end %>

app/views/inventories/edit.html.erb
<h1>発注の更新</h1>

<%= render 'inventories/form' %>

app/views/inventories/index.html.erb
<%= form_for(@stock) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :asin, placeholder: "ASINを入力してください" %>
  </div>
  <div class="field">
    <%= f.number_field :volume, placeholder: "個数を入力してください" %>
  </div>
  <div class="field">
    <%= f.number_field :price, placeholder: "1個当たりの価格を入力してください" %>
  <div class="field">
    <%= f.number_field :shipfee , placeholder: "送料を入力してください"%>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>
<%= form_for :stocks, url: arrived_inventories_path, method: 'patch' do |f| %>
　<%= f.submit "到着", class: "btn btn-large btn-primary" %>
　<% if current_user.inventories.any? %>
      <ol class="stocks">
      <div  class="tabele-responsive">
      <table class="table">
        <thead>
          <tr>
            <th>発注日</th>
            <th>ASIN</th>
            <th>商品名</th>
            <th>発注数</th>
            <th>仕入れ価格</th>
            <th>送料</th>
            <th>仕入れ先</th>
            <th>前月推定販売個数</th>
            <th>配送業者</th>
            <th>追跡番号</th>
            <th>予定到着日</th>
            <th>更新</th>
            <th>到着</th>
          </tr>
        </thead>
        <% @stocks.each do |stock| %>
        <tbody>
          <tr>
            <td><%= stock.created_at %></td>
            <td><%= stock.asin %></td>
            <td><%#= Asin.find_by(asin: stock.asin).title%></td>
            <td><%= stock.volume %></td>
            <td><%= stock.price %></td>
            <td><%= stock.shipfee%></td>
            <td><%=  %></td>
            <td><%=  %></td>
            <td><%=  %></td>
            <td><%=  %></td>
            <td><%=  %></td>
            <td><%= link_to "edit" , edit_inventory_path(stock) %></td>
            <td><%= check_box_tag "stock_ids[]",stock.id %></td>
            </tr>
        </tbody>
        <% end %>
      </table>
  　　</div>
      </ol>
    <% end %>
<% end %>

app/views/inventories/show.html.erb
<% if current_user.inventories.any? %>
      <ol class="stocks">
      <div  class="tabele-responsive">
      <table class="table">
        <thead>
          <tr>
            <th>発注日</th>
            <th>ASIN</th>
            <th>商品名</th>
            <th>発注数</th>
            <th>仕入れ価格</th>
            <th>送料</th>
            <th>仕入れ先</th>
            <th>前月推定販売個数</th>
            <th>配送業者</th>
            <th>追跡番号</th>
            <th>予定到着日</th>
          </tr>
        </thead>
        <% @arrived_stocks.each do |stock| %>
        <tbody>
          <tr>
            <td><%= stock.created_at %></td>
            <td><%= stock.asin %></td>
            <td><%#= Asin.find_by(asin: stock.asin).title%></td>
            <td><%= stock.volume %></td>
            <td><%= stock.price %></td>
            <td><%= stock.shipfee%></td>
            <td><%=  %></td>
            <td><%=  %></td>
            <td><%=  %></td>
            <td><%=  %></td>
            <td><%=  %></td>
            </tr>
        </tbody>
        <% end %>
      </table>
  　　</div>
      </ol>
    <% end %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "ManageAmazon", orders_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              売上配送・在庫管理 <b class="caret"></b>
            </a>
          <ul class="dropdown-menu">
            <li><%= link_to "仕入れ最安検索", lowests_path %></li>
            <li><%= link_to "在庫一覧", arrived_list_inventories_path %></li>
            <li><%= link_to "発注一覧", inventories_path %></li>
            <li><%= link_to "売上未配送一覧", orders_path %></li>
          </ul>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              出品 <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "ASIN登録パネル", asins_path %></li>
              <li><%= link_to "出品一覧", skus_path %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ManageAmazon</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
      <%= yield %>
    </div>
</body>
</html>

app/views/login_page/home.html.erb
<h1>LoginPage#home</h1>
<p>Find me in app/views/login_page/home.html.erb</p>

app/views/lowests/index.html.erb
<%= form_for(@lowest) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_field :asin, placeholder: "最安を検索したいASINを入力してください" %>
  </div>
  <%= f.submit "検索", class: "btn btn-primary" %>
<% end %>
<div  class="tabele-responsive">
    <table class="table">
        <thead>
          <tr>
            <th>ASIN</th>
            <th>商品名</th>
            <th>amazon</th>
            <th>yodobashi</th>
            <th>Rakuten</th>
            <th>yahoo!</th>
            <th>kakaku.com</th>
            <th>ES</th>
            <th>US</th>
            <th>CA</th>
            <th>MX</th>
            <th>JP</th>
            <th>仕入れ価格</th>
          </tr>
        </thead>
        <% @lowests.each do |lowest| %>
        <tbody>
          <tr>
            <td><%= lowest.created_at %></td>
            <td><%= Asin.find_by(asin: lowest.asin).title %></td>
            <td><%= lowest.amazon %></td>
            <td><%= %></td>
            <td><%=  %></td>
            <td><%= %></td>
            <td><%=  %></td>
            <td><%=  %></td>
            <td><%=  %></td>
            <td><%=  %></td>
            <td><%=  %></td>
          </tr>
       </tbody>
       <% end %>
　　</table>
</div>

app/views/orders/index.html.erb
<%= form_for :orders, url: update_all_orders_path, method: 'patch' do |f| %>
  <%= select_tag 'shipping_way',options_for_select(['小型SAL','SAL','Pメール','Dメール','EMS']) %>
  <%= text_field_tag 'shipping_fee' %>
　<%= f.submit "配送", class: "btn btn-large btn-primary" %>
　<% if current_user.orders.any? %>
      <ol class="orders">
      <div  class="tabele-responsive">
      <table class="table">
        <thead>
          <tr>
            <th>日付</th>
            <th>order_id</th>
            <th>国</th>
            <th>SKU</th>
            <th>ASIN</th>
            <th>商品名</th>
            <th>販売個数</th>
            <th>売上</th>
            <th>手数料</th>
            <th>入金額</th>
            <th>仕入れ</th>
            <th>粗利益</th>
            <th>送料</th>
            <th>利益率</th>
            <th>出荷</th>
          </tr>
        </thead>
        <% @orders.each do |order| %>
        <tbody>
          <tr>
            <td><%= order.created_at %></td>
            <td><%= order.order_id %></td>
            <td><%= order.country %></td>
            <td><%= order.sku %></td>
            <td><%= Asin.find_by(sku: order.sku).asin %></td>
            <td><%= Asin.find_by(sku: order.sku).title %></td>
            <td><%= order.volume %></td>
            <td><%= order.sold_price %></td>
            <td><%= order.fee %></td>
            <td><%= order.sold_price.to_f+order.fee.to_f %></td>
            <td><%=  %></td>
            <td><%= order.fee %></td>
            <td><%=  %></td>
            <td><%= order.fee %></td>
            <td><%= check_box_tag "order_ids[]",order.id %></td>
          </tr>
        </tbody>
        <% end %>
      </table>
  　　</div>
      </ol>
    <% end %>
  </div>
</div>
<% end %>
　<% if current_user.orders.any? %>
      <ol class="orders">
      <div  class="tabele-responsive">
      <table class="table">
        <thead>
          <tr>
            <th>日付</th>
            <th>order_id</th>
            <th>国</th>
            <th>SKU</th>
            <th>ASIN</th>
            <th>商品名</th>
            <th>販売個数</th>
            <th>売上</th>
            <th>手数料</th>
            <th>入金額</th>
            <th>仕入れ</th>
            <th>粗利益</th>
            <th>送料</th>
            <th>利益率</th>
            <th>出荷</th>
          </tr>
        </thead>
        <% @shipped_orders.each do |order| %>
        <tbody>
          <tr>
            <td><%= order.created_at %></td>
            <td><%= order.order_id %></td>
            <td><%= order.country %></td>
            <td><%= order.sku %></td>
            <td><%= Asin.find_by(sku: order.sku).asin %></td>
            <td><%= Asin.find_by(sku: order.sku).title %></td>
            <td><%= order.volume %></td>
            <td><%= order.sold_price %></td>
            <td><%= order.fee %></td>
            <td><%= order.sold_price.to_f+order.fee.to_f-order.shipfee.to_f %></td>
            <td><%=  %></td>
            <td><%= order.fee %></td>
            <td><%=  order.shipfee %></td>
            <td><%= order.fee %></td>
            </tr>
        </tbody>
        <% end %>
      </table>
  　　</div>
      </ol>
    <% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/skus/index.html.erb
<!--<p>
  Download:
  <%#S= link_to "Excel", skus_path(@skus format: "xls") %>
</p>-->
<ol class="stocks">
      <div  class="tabele-responsive">
      <table class="table">
        <thead>
          <tr>
            <th>SKU</th>
            <th>ASIN</th>
            <th>商品名</th>
            <th>UK</th>
            <th>DE</th>
            <th>FR</th>
            <th>IT</th>
            <th>ES</th>
            <th>US</th>
            <th>CA</th>
            <th>MX</th>
            <th>JP</th>
            <th>仕入れ価格</th>
          </tr>
        </thead>
        <% @skus.each do |stock| %>
        <tbody>
          <tr>
            <td><%= stock.created_at %></td>
            <td><%= stock.asin %></td>
            <td><%#= Asin.find_by(asin: stock.asin).title%></td>
            <td><%= stock.volume %></td>
            <td><%= stock.price %></td>
            <td><%= stock.shipfee%></td>
            <td><%=  %></td>
            <td><%=  %></td>
            <td><%=  %></td>
            <td><%=  %></td>
            <td><%=  %></td>
            </tr>
        </tbody>
        <% end %>
      </table>
  　　</div>
</ol>

app/views/users/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %> 
      <%= f.label :name,'名前' %>
      <%= f.text_field :name %>
      
      <%= f.label :email,'メールアドレス' %>
      <%= f.email_field :email %>
      
      <%= f.label :prefecture,'都道府県'  %>
      <%= f.select :prefecture,options_for_select(['北海道','青森','岩手','宮城','秋田','山形','福島','茨城','栃木','群馬','埼玉','千葉','東京','神奈川','新潟','富山','石川','福井','山梨','長野','岐阜','静岡','愛知','三重','滋賀','京都','大阪','兵庫','奈良','和歌山','鳥取','島根','岡山','広島','山口','徳島','香川','愛媛','高知','福岡','佐賀','長崎','熊本','大分','宮崎','鹿児島','沖縄'], @user.prefecture), {}, { :class => 'form-control' } %>
      <%#ゆくゆくは、DBで登録多い順で都道府県を並べたい%>
      <%= f.label :phone ,'電話番号' %>
      <%= f.text_field :phone ,placeholder: "ハイフンの入力はいりません"%>
      
      <%= f.label :password ,'パスワード' %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "もう一度入力をお願いします。" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create mcy account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<h1>基本情報の編集</h1>

<%= render 'form' %>

app/views/users/new.html.erb
<h1>新規登録</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
    　<%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= form_for(@order) do |f| %>
  <%= f.label :how,"配送方法"%>
  <%= f.select :how,options_for_select(['小型SAL','SAL','Pメール','Dメール','EMS'], @order.area), {}, { :class => 'form-control' } %>
  <%= f.label :ship_fee %>
  <p><%= f.text_area :ship_fee, class: 'form-control' %>円</p>
　<%= f.submit "配送", class: "btn btn-large btn-primary" %>
　<% if @user.orders.any? %>
      <ol class="orders">
      <div  class="tabele-responsive">
      <table class="table">
        <thead>
          <tr>
            <th>日付</th>
            <th>order_id</th>
            <th>国</th>
            <th>SKU</th>
            <th>ASIN</th>
            <th>商品名</th>
            <th>販売個数</th>
            <th>売上</th>
            <th>手数料</th>
            <th>入金額</th>
            <th>仕入れ</th>
            <th>粗利益</th>
            <th>送料</th>
            <th>利益率</th>
            <th>出荷</th>
          </tr>
        </thead>
        <% @orders.each do |order| %>
        <tbody>
          <tr>
            <td><%= order.created_at %></td>
            <td><%= order.order_id %></td>
            <td><%= order.country %></td>
            <td><%= order.sku %></td>
            <td><%= Asin.find_by(sku: order.sku).asin %></td>
            <td><%= Asin.find_by(sku: order.sku).title %></td>
            <td><%= order.volume %></td>
            <td><%= order.sold_price %></td>
            <td><%= order.fee %></td>
            <td><%= order.sold_price.to_f+order.fee.to_f %></td>
            <td><%=  %></td>
            <td><%= order.fee %></td>
            <td><%=  %></td>
            <td><%= order.fee %></td>
            <td><input type="checkbox" /></td>
          </tr>
        </tbody>
        <% end %>
      </table>
  　　</div>
      </ol>
    <% end %>
  </div>
</div>
<% end %>